# Expects Debian Jessie
---
- hosts: all
  tasks:
    - name: Enabling debian backports
      command: bash -c 'echo "deb http://http.debian.net/debian jessie-backports main" > /etc/apt/sources.list.d/backports.list'
        creates=/etc/apt/sources.lists.d/backports.list
    - name: Update system
      apt:
        update_cache=true
        upgrade=dist
    - name: Installing rsync
      apt:
        name=rsync
    - name: Ensure directory exists
      file:
        path=/tmp/dillinger
        state=directory
        mode=0755
    - name: Uploading project
      synchronize:
        src=.
        dest=/tmp/dillinger
        recursive=yes
        delete=yes
    - name: Installing docker-py
      apt:
        name=python-docker
    - name: Installing docker
      apt:
        name=docker.io
    - name: Build dillinger
      docker_image:
        name=joemccann/dillinger
        tag=latest
        path=/tmp/dillinger
        state=build
    - name:
      command: cp /tmp/dillinger/dillinger.service /etc/systemd/system
        creates=/etc/systemd/system/dillinger.service
    - service:
        name=dillinger
        state=started
